name: webtheek
services:
  - name: webtheek
    build_command: npm run build
    environment_slug: node-js
    http_port: 8080
    image:
      #registry: registry.digitalocean.com/webtheek-container/app
      registry_type: DOCR
      repository: app
      #registry: ghcr.io
      #registry_type: GHCR
      #repository: alvaroruizmontaner/webtheek
      tag: 1.0.0
    instance_count: 1
    instance_size_slug: basic-xxs
    run_command: npm start
    source_dir: /
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_STRIPE_API_SECRET
        value: $NEXT_PUBLIC_STRIPE_API_SECRET
      - key: NEXT_PUBLIC_API_URL
        value: $NEXT_PUBLIC_API_URL

